import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Orbitron } from 'next/font/google'
import "./globals.css";
import { CartProvider } from "@/components/sections/Cart";

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ["400", '700']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cheel Keyboard",
  description: "Generated by Cheel Company Ltd.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth bg-stone-950 h-full">
      <CartProvider>
        <body className={orbitron.className}>
          {children}
        </body>
      </CartProvider>
    </html>
  );
}
